### ISSUE TITLE
Can't build nfd on OSX10.14 using gmake_macosx

### ISSUE THREAD

**Issue by jackkilgore** [mlabbe/nativefiledialog#88]
**Compilation Environment**

 - OS : OSX 10.14
 - Compiler (eg: GCC, Clang): Clang
 - Compiler Version (eg: MSVC 2017):  11.0
 - Build directory used (eg: `build/gmake_linux`:
 - Have I attempted to reproduce the problem on the `devel` branch?
Yes
**Describe the bug**
Running the command make config=release_x64 fails to build the static library. It seems to not be able to find AppKit. I have gotten around this issue by using the xcode builder. Note that the above command works on OSX10.12.

**Compilation output**

==== Building nfd (release_x64) ====
nfd_cocoa.m
clang   -MMD -MP -DNDEBUG -I../../src/include -m64 -O2 -Wall -Wextra -fno-exceptions  -o "obj/x64/Release/nfd/nfd_cocoa.o" -MF "obj/x64/Release/nfd/nfd_cocoa.d" -c "../../src/nfd_cocoa.m"
../../src/nfd_cocoa.m:7:10: fatal error: 'AppKit/AppKit.h' file not found
#include <AppKit/AppKit.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [obj/x64/Release/nfd/nfd_cocoa.o] Error 1
make: *** [nfd] Error 2

**Additional context**

When using the xcode command it causes NFD to crash on OSX's before 10.14.

**User Description**

Using this for a small open source project with UCSB.

**Comment by mlabbe** [comment]
Your build environment is not including a core system header.  I can't reproduce this, so it must be environmental.
